env:
  es6: true
  node: true
  mocha: true
  browser: true
parser: '@typescript-eslint/parser'
ignorePatterns:
  - 'test/helpers/compileFiles/*'
  - 'test/helpers/initializeMocha.ts'
  - 'dist/*'
  - 'karma.conf.js'
plugins:
  - 'import'
  - '@typescript-eslint'
extends:
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:import/errors'
  - 'plugin:import/warnings'
  - 'airbnb-typescript/base'
settings:
  'import/extensions': ['.ts', '.js']
  'import/parsers':
    '@typescript-eslint/parser': ['.ts', '.js']
  'import/resolver':
    node:
      extensions: ['.ts', '.js']
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  project: './tsconfig.test.json'
  ecmaVersion: 2018
  sourceType: module
rules:
  # turn off indentation for eslint, apparently conflicts with typescript linter (which will also lint javascript)
  indent: 'off'
  # set indentation rules for 2 spaces to combat conflict between airbnb and typscript settings
  '@typescript-eslint/indent': ['error', 2]
  '@typescript-eslint/no-object-literal-type-assertion': 0
  'import/prefer-default-export': 0
  'import/no-extraneous-dependencies': ['error', {'devDependencies': true}]
  'import/no-cycle': 0
  'import/no-plusplus': 0
