"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.OPEN_PARENTHESES = exports.CLOSING_CURLY = exports.OPENING_CURLY = exports.SINGLE_QUOTE = exports.QUOTATION_MARK = exports.SEMICOLON = exports.SPACE = exports.EMPTY_STRING = exports.PERIOD = exports.IMPORT_DECLARATION = exports.FUNCTION_DECLARATION = exports.VARIABLE_DECLARATION = void 0;
var VARIABLE_DECLARATION = 'var';
exports.VARIABLE_DECLARATION = VARIABLE_DECLARATION;
var FUNCTION_DECLARATION = 'function';
exports.FUNCTION_DECLARATION = FUNCTION_DECLARATION;
var IMPORT_DECLARATION = 'require';
exports.IMPORT_DECLARATION = IMPORT_DECLARATION;
var PERIOD = '.';
exports.PERIOD = PERIOD;
var EMPTY_STRING = '';
exports.EMPTY_STRING = EMPTY_STRING;
var SPACE = ' ';
exports.SPACE = SPACE;
var SEMICOLON = ';';
exports.SEMICOLON = SEMICOLON;
var QUOTATION_MARK = '"';
exports.QUOTATION_MARK = QUOTATION_MARK;
var SINGLE_QUOTE = '\'';
exports.SINGLE_QUOTE = SINGLE_QUOTE;
var OPENING_CURLY = '{';
exports.OPENING_CURLY = OPENING_CURLY;
var CLOSING_CURLY = '}';
exports.CLOSING_CURLY = CLOSING_CURLY;
var OPEN_PARENTHESES = '(';
exports.OPEN_PARENTHESES = OPEN_PARENTHESES;